# -*- coding: utf-8 -*-
"""map reduce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nI7cxl1fFrxPeLJ5wlvekaiVqLNMrQR4
"""

# map-->it is a generator which will compute the value according to the user request
mylist=[10,20,30]
def square(num):
  return num**2
out=map(square,mylist)
next(out)

mylist=[10,20,30]
def square(num):
  return num**2
list(map(square,mylist))
# list-->compute all values in a single time

list(map(lambda num:num**2,mylist))

list(map(lambda num:num%3==0,mylist))
# map return each value

list(filter(lambda num:num%3==0,mylist))
# filter return the true values only

#Exceptional handling
# try:code to run
#except:how the error will be handled
#finally-->this block always run whether there is any error or not
try:
  print(10)
  print("hey"+20)
  print(num123)
except (NameError,TypeError) as e:
  print("error occured",e)
except Exception as e:
  print("All error occured",e)
finally:
  print("hey")

